### PR TITLE
Update eslint

### PR DESCRIPTION
**Pull request by sam-github**

### CODE REVIEW

**Comment by pthieu** [comment]
@sam-github: LGTM. Didn't know jscs merged with eslint.

**Comment by sam-github** [comment]
@pthieu it didn't merge, per se, but eslint does all the good stuff it used to

**Comment by sam-github** [comment]
@slnode test please

**Comment by pthieu** [comment]
@sam-github: wait really: on their GH page, it says they did: https://github.com/jscs-dev/node-jscs

**Comment by sam-github** [comment]
@pthieu oh, yeah. sorry, forgot about that!

**Comment by sam-github** [comment]
```
TAP version 13
# Subtest: ./test/test-exposed-properties.js
    # Subtest: master should expose
        # Subtest: cpu count, for easy use as a default size
            ok 1 - should be equal
            1..1
        ok 1 - cpu count, for easy use as a default size # time=17.416ms

        # Subtest: master process start time
            ok 1 - expect truthy value
            1..1
        ok 2 - master process start time # time=5.98ms

        # Subtest: message cmd names in master
            ok 1 - should be equal
            1..1
        ok 3 - message cmd names in master # time=5.786ms

        1..3
    ok 1 - master should expose # time=42.009ms

    1..0
not ok 1 - ./test/test-exposed-properties.js # time=460.322ms
```

the node 0.10 windows failed on the simplest test.... it seemed to think that there were zero tests, which is strange, it should end in `1..1`, which is does elsewhere

**Pull request merged**
